name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
     - completed
    branches:
      - "develop"
      - "main"

env:
  IMAGE_SERVER: ghcr.io/${{ github.repository }}-server
  IMAGE_CLIENT: ghcr.io/${{ github.repository }}-client

jobs:

  staging-mode:
    name: staging

    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop'
    runs-on: ubuntu-latest
    
    environment:
      name: staging
      url: ${{ vars.PUBLIC_URL}}

    steps:
      - name: Staging - SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Inisiasi folder..."
            REPO_DIR="/home/${{ vars.EC2_USER }}/app"
            mkdir -p $REPO_DIR
            if [ ! -d "$REPO_DIR/.git" ]; then
              git clone https://github.com/${{ github.repository }}.git $REPO_DIR
            fi
            cd $REPO_DIR

            cat > .env <<-EOF
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            CORS_ORIGIN=${{ vars.CORS_ORIGIN }}
            IMAGE_TAG=develop
            EOF

            source .env

            git checkout develop
            git pull origin develop

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            docker pull ${{ env.IMAGE_SERVER }}:$IMAGE_TAG
            docker pull ${{ env.IMAGE_CLIENT }}:$IMAGE_TAG 

            # echo "Run Migration..."
            
            # docker compose -f docker-compose.yaml -f docker-compose.prod.yaml run --rm backend node ./node_modules/typeorm/cli.js migration:run -d dist/db/data-source.js

            echo "Run All Service..."

            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --remove-orphans

            sleep 20
            curl --fail -s "${{ vars.PUBLIC_URL }}/health" || (echo "Health check gagal!" && exit 1) 

  prod-mode:
    name: Deployment to Production

    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: ${{ vars.PUBLIC_URL}}

    steps:
      - name: Production - SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            REPO_DIR="/home/${{ vars.EC2_USER }}/app"
            mkdir -p $REPO_DIR

            if [ ! -d "$REPO_DIR/.git" ]; then
              git clone https://github.com/${{ github.repository }}.git $REPO_DIR
            fi

            cd $REPO_DIR

            cat > .env <<-EOF
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            CORS_ORIGIN=${{ vars.CORS_ORIGIN }}
            IMAGE_TAG=latest
            EOF

            source .env

            git checkout main

            git pull origin main

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            docker pull ${{ env.IMAGE_SERVER }}:$IMAGE_TAG
            docker pull ${{ env.IMAGE_CLIENT }}:$IMAGE_TAG

            echo "Run Migration..."
            
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml run --rm backend node ./node_modules/typeorm/cli.js migration:run -d dist/db/data-source.js


            echo "Run All Service..."

            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --remove-orphans

            sleep 20
            curl --fail -s "${{ vars.PUBLIC_URL }}/health" || (echo "Health check gagal!" && exit 1) 